mapa-de-rondonia/config/routes.rb
Rails.application.routes.draw do
  resources :maps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mapa-de-rondonia/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mapa-de-rondonia/app/models/map.rb
class Map < ApplicationRecord
end

mapa-de-rondonia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mapa-de-rondonia/app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:zoom)
    end
end

mapa-de-rondonia/app/helpers/application_helper.rb
module ApplicationHelper
end

mapa-de-rondonia/app/helpers/maps_helper.rb
module MapsHelper
end

mapa-de-rondonia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapaDeRondonia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mapa-de-rondonia/app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zoom %>
    <%= form.text_field :zoom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mapa-de-rondonia/app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

mapa-de-rondonia/app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>
<style>
#mapid { height: 500px }
.info {
    padding: 6px 8px;
    font: 14px/16px Arial, Helvetica, sans-serif;
    background: white;
    background: rgba(255,255,255,0.8);
    box-shadow: 0 0 15px rgba(0,0,0,0.2);
    border-radius: 5px;
}
.info h4 {
    margin: 0 0 5px;
    color: #777;
}
</style>
<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>Zoom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.zoom %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

 <div id="mapid">
 </div>
 <script>
 var cacoal = L.marker([-11.4330519, -61.4793381]).bindPopup('This is Cacoal, CO.');
 var cities = L.layerGroup([cacoal]);
 var mbAttr = 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>';
  var info = L.control();
 function highlightFeature(e) {
    var layer = e.target;

    layer.setStyle({
        weight: 5,
        color: '#666',
        dashArray: '',
        fillOpacity: 0.7
    });

    if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
        layer.bringToFront();
    }
    info.update(layer.feature.properties);
}
function resetHighlight(e) {
   geojson = L.geoJson(ro, {style: style, onEachFeature: onEachFeature});
   geojson.resetStyle(e.target);
   info.update();
}
function zoomToFeature(e) {
    mymap.fitBounds(e.target.getBounds());
}
function onEachFeature(feature, layer) {
    layer.on({
        mouseover: highlightFeature,
        mouseout: resetHighlight,
        click: zoomToFeature
    });
}
 function getColor(d) {
    return d > 1000 ? '#800026' :
           d > 500  ? '#BD0026' :
           d > 200  ? '#E31A1C' :
           d > 100  ? '#FC4E2A' :
           d > 50   ? '#FD8D3C' :
           d > 20   ? '#FEB24C' :
           d > 10   ? '#FED976' :
                      '#FFEDA0';
}
function style(feature) {
    return {
        fillColor: getColor(feature.properties.death),
        weight: 2,
        opacity: 1,
        color: 'white',
        dashArray: '3',
        fillOpacity: 0.7
    };
}
info.onAdd = function (mymap) {
    this._div = L.DomUtil.create('div', 'info'); // create a div with a class "info"
    this.update();
    return this._div;
};

// method that we will use to update the control based on feature properties passed
info.update = function (props) {
    this._div.innerHTML = '<h4>Taixa de Óbito</h4>' +  (props ?
        '<b>' + props.name + '</b><br />' + props.death + ''
        : 'Hover over a state');
};
 var mymap = L.map('mapid').setView([-11.4330519, -61.4793381], 7.20,   [cities]);
 L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiaWdvcmtlZmthIiwiYSI6ImNrYTJxYjc2cDA5b28zZm54ZGFvdmNhaHMifQ.z_lv6RVfZ1ituAx3v5cnnQ', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox/streets-v11',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'pk.eyJ1IjoiaWdvcmtlZmthIiwiYSI6ImNrYTJxYjc2cDA5b28zZm54ZGFvdmNhaHMifQ.z_lv6RVfZ1ituAx3v5cnnQ'
}).addTo(mymap);
var baseMaps = {
};

var overlayMaps = {
    "Cities": cities
};
L.geoJson(ro, {style: style, onEachFeature: onEachFeature}).addTo(mymap);

info.addTo(mymap);
L.control.layers(baseMaps, overlayMaps).addTo(mymap);
element = document.getElementsByClassName("leaflet-control-layers-selector")[0].click();
 </script>

mapa-de-rondonia/app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

mapa-de-rondonia/app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zoom:</strong>
  <%= @map.zoom %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>